### ISSUE TITLE
There is no emoji for UTC

### ISSUE THREAD

**Issue by alvinlindstam** [EmilStenstrom/emojizones#1]
I suggest 🦄

**Comment by EmilStenstrom** [comment]
@alvinlindstam Great idea. Is the rationale “The unicorn we all dream of, a world without time zones”?

**Comment by alvinlindstam** [comment]
Yeah, something like that. Or something like ”fictional and non-realistic fairy tale creature, much like programmers’ idea that time processing should be easy”

**Comment by EmilStenstrom** [comment]
Added! :)
